#!/usr/bin/env python3
"""Completed B/L same-scene comparison with target-implied palm evidence. CPU only."""
import sys
sys.dont_write_bytecode=True
from pathlib import Path
import json,hashlib,collections,csv
import numpy as np
from scipy.spatial.transform import Rotation
ROOT=Path(__file__).resolve().parent;EXPERIMENT=ROOT.parent

def load(p):return json.loads(Path(p).read_text())
def sha(p):return hashlib.sha256(Path(p).read_bytes()).hexdigest()
def margins(xyz):
 x,y,z=xyz;v=dict(x=.025-abs(x),y=.04-abs(y),z_lower=z-.065,z_upper=.125-z)
 return dict(min_m=float(min(v.values())),axes_m={k:float(x)for k,x in v.items()},inside=all(x>0 for x in v.values()))
def target_evidence(r):
 g=r['grasp_after'];a=g['planned_apple'];rh=Rotation.from_quat(g['hand_quaternion_world']).as_matrix();rt=Rotation.from_quat(r['measured_quaternion']).as_matrix();tcp_offset=rh.T@(np.asarray(g['tcp_position_world'])-g['hand_position_world']);tcp_rotation_in_hand=rh.T@rt;desired_hand_rotation=np.asarray(r['target_rotation'])@tcp_rotation_in_hand.T;desired_hand_position=np.asarray(r['target_position'])-desired_hand_rotation@tcp_offset;target_local=desired_hand_rotation.T@(np.asarray(a['world_position'])-desired_hand_position);actual=np.asarray(a['hand_local_position']);assert np.allclose(rh.T@(np.asarray(a['world_position'])-g['hand_position_world']),actual,atol=1e-10,rtol=0)
 return dict(step=r['control_step'],chunk_id=r['chunk_id'],target_k=r['target_k'],planned_apple_id=a['apple_id'],held_apple_id=g['held_apple_id'],target_implied_palm_xyz_m=target_local.tolist(),actual_palm_xyz_m=actual.tolist(),target_implied_margins=margins(target_local),actual_margins=margins(actual),target_width_m=r['target_width'],actual_width_m=g['measured_width_m'],gripper_intent=g['gripper_intent'],both_fingers_contact=a['both_fingers_contact'],tracking_position_error_m=r['position_error_m'],tracking_rotation_error_rad=r['rotation_error_rad'],advance_reason=r['advance_reason'],ik_failed=r['info']['ik_failed'],tcp_offset_in_hand_m=tcp_offset.tolist())

def main():
 source=ROOT/'closed_loop_final/failure_evidence.json';allresults=load(source);assert allresults['status']=='COMPLETE' and len(allresults['rows'])==52 and not allresults['pending'];rows=allresults['rows'];pairs=[]
 for b in [x for x in rows if x['stage']=='B30']:
  l=next(x for x in rows if x['stage']=='L30' and x['scene_seed']==b['scene_seed']);pairs.append(dict(scene_seed=b['scene_seed'],split=b['split'],B=dict(outcome=b['outcome'],first_grasp=b['first_grasp_step'],held15=b['held15'],strict=b['strict_success'],fruits=b['fruits']),L=dict(outcome=l['outcome'],first_grasp=l['first_grasp_step'],held15=l['held15'],strict=l['strict_success'],fruits=l['fruits']),held15_delta=int(l['held15'])-int(b['held15'])))
 focus={}
 for arm,stage in [('B','B30'),('L','L30')]:
  case=next(x for x in rows if x['stage']==stage and x['scene_seed']==2014362);folder=Path(case['path']);done=load(folder/'completed.json');assert sha(folder/'steps.jsonl')==done['files_sha256']['steps.jsonl'];steps=[json.loads(l)for l in(folder/'steps.jsonl').read_text().splitlines()];chosen=[71,84,85,93,94]if arm=='B'else[68,84,85,99,145,210];focus[arm]=dict(case=case,evidence=[target_evidence(steps[i-1])for i in chosen],first120=[target_evidence(r)for r in steps[:120]],target_geometry_note='Raw chunk TCP goal converted to implied hand frame using observed fixed TCP/hand transform and current POST-boundary fruit position. This is a diagnostic hypothetical target geometry, not an executed pose or prediction of future fruit dynamics. Actual fruit identity/contact/held are observed separately.')
 damage=[dict(stage=x['stage'],scene_seed=x['scene_seed'],branch_break_count=x['branch_break_count'])for x in rows if x['branch_break_count']]
 regression=[x for x in rows if x['stage']in['regression_B30','regression_L30']];result=dict(status='COMPLETE',source=str(source),source_sha256=sha(source),scene_pairs=pairs,focus_2014362=focus,regression=regression,branch_damage=damage,interpretation=['Development8 uses one inference seed42, includes2training scenes, and has been inspected during development. Held6->7 is one additional boundary-sensitive scene, not evidence of robust generalization.','L improves actual palm geometry in2014362 sufficiently to cross the attach threshold atstep85; this agrees with local improvement even though pooled expert-state prediction errors mostly worsened.','At Bstep93 raw goal-implied palm geometry is inside, actual palm remains2.007mm outside inx and tracking position error is10.251mm. That shows target prediction and target tracking both matter, without proving a tolerance change alone will fix it.','At Lstep85 actualx20.060mm gives4.940mm xmargin; fruit13 held15 at99, detached145, released210 about0.915m frombucket. Additional grasp does not complete the task.','Historical auxiliary scene2010600 seed42 shows one real complete release60 success, but seed43 regresses from Bgrasp toLNO_GRASP; report both, not a selected success.','Offline means are smooth distances to one teacher trajectory; grasp/placement are thresholded closed-loop events on model-visited states. Their rankings can differ without contradiction.'])
 out=ROOT/'endpoint_closed_loop_cases.json'
 with out.open('x')as f:json.dump(result,f,indent=2,allow_nan=False);f.write('\n')
 with(ROOT/'scene2014362_target_actual_palm.csv').open('x',newline='')as f:
  names=['arm','step','target_k','held_apple_id','target_palm_x_mm','actual_palm_x_mm','target_margin_mm','actual_margin_mm','target_width_mm','actual_width_mm','position_error_mm','rotation_error_rad','closing','dual_contact'];w=csv.DictWriter(f,fieldnames=names);w.writeheader()
  for arm,d in focus.items():
   for e in d['first120']:w.writerow(dict(arm=arm,step=e['step'],target_k=e['target_k'],held_apple_id=e['held_apple_id'],target_palm_x_mm=e['target_implied_palm_xyz_m'][0]*1000,actual_palm_x_mm=e['actual_palm_xyz_m'][0]*1000,target_margin_mm=e['target_implied_margins']['min_m']*1000,actual_margin_mm=e['actual_margins']['min_m']*1000,target_width_mm=e['target_width_m']*1000,actual_width_mm=e['actual_width_m']*1000,position_error_mm=e['tracking_position_error_m']*1000,rotation_error_rad=e['tracking_rotation_error_rad'],closing=e['gripper_intent']<0,dual_contact=e['both_fingers_contact']))
 text='''本轮完整闭环与离线误差的关系\n\n完整52条结果：GT30/GT5各8严格成功；开发B30持15为6/8、L30为7/8，严格成功都0；B5/L5均0/8持果。历史成功场景单独报告，B两种子都是持果入桶未释放，L seed42完成同果实release+bucket60，L seed43无抓。\n\n开发集增加的唯一抓持场景是2014362（val episode001190、推理seed42）：\nB首次负intent step71；在有双指接触和closing的最佳未抓边界step93，掌内x=27.007mm，超过25mm上限2.007mm；raw目标对应的掌内x=16.837mm、最小裕量8.163mm，但实际位置跟踪误差10.251mm、旋转误差0.02369rad。原始目标可在掌内并不保证此刻真实状态已在掌内。\nL首次负intent step68；step84实际x=25.260mm、越界0.260mm，step85实际x=20.060mm、x裕量4.940mm并抓持fruit13。step85 raw目标对应x=14.524mm、最小裕量10.476mm，实际位置误差7.166mm；命令/实际开度42.68/47.39mm。两组这些边界均无IK失败。\nL随后step99满足held15、145摘离、210释放，离桶体积约0.915m，未进入桶，因此本次增加抓持并未形成完整放置。\n\n该例当前seed42首段位置对教师误差first5略差52.26->55.07mm，但full30略好50.87->48.26mm；不能用全体场景、全部horizon或三seed平均替代局部接触时刻几何。原整体离线位置/旋转多数退化，与这一场景的阈值跨越不矛盾。smooth教师距离不等同于闭环抓持判据，也不能由一例跨阈值证明可靠泛化。\n\n历史aux scene2010600、seed42的L轨迹提供了一次完整闭环正证据：fruit26 step97首次抓持、111 held15、166摘离；639曾释放、640重新抓持，647再次释放后连续60边界在桶，706满足strict。seed43却完全未抓，B seed42/43原来均能抓持入桶；所以新能力存在但稳定性不足，不能只呈现成功seed。\n\nL5分支损伤：scene2015751记录2个断枝，其余7开发场景为0。短commit不只未改善抓取，此例还有额外损伤。\n\n目标掌坐标是用当前果实世界位置、已记录TCP/hand刚体关系，推算raw目标达成后的假想位置；它不是新的真实观察或未来果实运动预测。桶距离使用已记录初始base近似，入桶与释放判断采用fruit_state的同果实ID真值。\n\n本报告开发8条为已暴露集合且含2条训练episode，只有1个推理seed、1个训练seed；当前6->7只表示这一组配对多1例，不能称稳健泛化。fresh24没有被读取或测试。\n'''
 with(ROOT/'endpoint_closed_loop_cases.txt').open('x')as f:f.write(text)
 print(json.dumps(dict(status='COMPLETE',output=str(out),paired_dev8=len(pairs),additional_held=[p['scene_seed']for p in pairs if p['held15_delta']>0],regressions_held=[p['scene_seed']for p in pairs if p['held15_delta']<0],damage=damage),indent=2))
if __name__=='__main__':main()
